[package]
name = "coded-chars"
version = "0.1.0"
edition = "2021"
description = "A implementation of standards ECMA-35, ECMA-43 and ECMA-48"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
